package com.josiasmartins.spring_dynamodb_aws.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@DynamoDBTable(tableName = "tb_galaxia")
@Data
public class Galaxia {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "distance")
    private String distance;

    @DynamoDBAttribute(attributeName = "id_planet")
    private String idPlanet;



}
