package com.josiasmartins.spring_dynamodb_aws.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.josiasmartins.spring_dynamodb_aws.models.DTO.PlanetRequest;
import com.josiasmartins.spring_dynamodb_aws.repository.PlanetRepository;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@DynamoDBTable(tableName = "tb_planet")
@Data
@NoArgsConstructor
public class Planet {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "planet_childreen")
    private String planetChildren;

    public Planet(PlanetRequest planetRequest) {
        this.name = planetRequest.name();
        this.planetChildren = planetRequest.planetChildren();
    }

}
